version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:266735821233:task-definition/poc_td:1"  # Ensure this ARN is correct
        LoadBalancerInfo:
          ContainerName: "poc_cont"  # Ensure this matches your ECS container name
          ContainerPort: 8080        # Ensure this matches your ECS container port
Hooks:
  - BeforeInstall: "arn:aws:lambda:ap-south-1:266735821233:function:Before-install"
  - AfterInstall: "arn:aws:lambda:ap-south-1:266735821233:function:After-Install"
