version: 0.0
resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:266735821233:task-definition/my-td:1"
        LoadBalancerInfo:
          ContainerName: "my-cont"
          ContainerPort: 8080
          [
  {
    "containerDefinitions": [
      {
        "name": "my-ecs-app",
        "image": "266735821233.dkr.ecr.ap-south-1.amazonaws.com/myrepo",
        "memory": 512,
        "cpu": 256,
        "essential": true,
        "portMappings": [
          {
            "containerPort": 8080,
            "hostPort": 8080
          }
        ]
      }
    ],
    "family": "my-ecs-app"
  }
]
